from pathlib import Path
import re

INDEX=Path('web/index.html')
SW=Path('web/sw.js')
VERSION=Path('web/version.txt')
html=INDEX.read_text(encoding='utf-8')

MARKER='/* anonbox-light-ui-v6 */'
if MARKER in html:
    print('v6 already applied')
    raise SystemExit(0)

html=html.replace('<meta name="theme-color" content="#0a1019">','<meta name="theme-color" content="#f6f8fc">',1)

old='<div id="identityInfo" class="muted small">Ton identité ne sera pas envoyée au destinataire.</div><textarea id="messageBody"'
new='''<div id="identityInfo" class="muted small">Ton identité réelle ne sera pas envoyée au destinataire.</div><div id="anonIdentityPanel" class="anonIdentityPanel"><div class="anonIdentityCurrent"><div id="anonProfileAvatar" class="anonProfileAvatar">🕶️</div><div class="anonProfileSummary"><b id="anonProfileName">Sans profil</b><span id="anonProfileHint">Tu peux rester totalement anonyme ou utiliser un profil anonyme local.</span></div></div><div class="anonIdentityActions"><button id="anonEditProfile" type="button" class="secondary">Créer mon profil anonyme</button><button id="anonGenerateProfile" type="button" class="ghost">✨ Générer un profil</button><button id="anonToggleProfile" type="button" class="ghost hidden">Envoyer sans profil</button></div><div id="anonProfileEditor" class="anonProfileEditor hidden"><label>Nom ou pseudonyme anonyme<input id="anonProfileNameInput" maxlength="32" placeholder="Ex. Nova 428"></label><label>Image de profil<input id="anonProfileImageInput" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="anonEditorActions"><button id="anonProfileSave" type="button">Enregistrer</button><button id="anonProfileCancel" type="button" class="ghost">Annuler</button></div></div><div id="anonProfileStatus" class="status"></div></div><textarea id="messageBody"'''
if old not in html: raise SystemExit('identity panel anchor missing')
html=html.replace(old,new,1)

html=html.replace("ATTACHMENT_API=SUPABASE_URL+'/functions/v1/anonbox-attachment',BASE=", "ATTACHMENT_API=SUPABASE_URL+'/functions/v1/anonbox-attachment',ANON_AVATAR_API=SUPABASE_URL+'/functions/v1/anonbox-anonymous-avatar',BASE=",1)
html=html.replace("composerCounter=null;", "composerCounter=null,anonLocalProfile=null;",1)

inject=r'''function anonProfileStored(){try{var raw=localStorage.getItem('anonbox_anonymous_profile_v1');if(!raw)return null;var p=JSON.parse(raw);if(!p||!p.pseudonym)return null;return p}catch(e){return null}}
function saveAnonProfileLocal(p){anonLocalProfile=p||null;if(p)localStorage.setItem('anonbox_anonymous_profile_v1',JSON.stringify(p));else localStorage.removeItem('anonbox_anonymous_profile_v1');renderAnonProfilePanel()}
function activeAnonProfile(){var p=anonLocalProfile||anonProfileStored();if(!p||p.enabled===false)return null;return p}
function anonProfilePayload(){var p=activeAnonProfile();return p?{pseudonym:String(p.pseudonym||'').trim(),avatar_path:p.avatar_path||null}:null}
function renderAnonProfilePanel(){var panel=$('anonIdentityPanel');if(!panel)return;panel.classList.toggle('hidden',sendMode!=='anonymous');if(sendMode!=='anonymous')return;anonLocalProfile=anonLocalProfile||anonProfileStored();var p=anonLocalProfile,active=p&&p.enabled!==false,name=$('anonProfileName'),hint=$('anonProfileHint'),av=$('anonProfileAvatar'),toggle=$('anonToggleProfile'),edit=$('anonEditProfile');if(p){name.textContent=p.pseudonym;hint.textContent=active?'Profil anonyme actif · ton compte et ton e-mail restent cachés.':'Profil enregistré mais désactivé pour l’envoi.';av.innerHTML=p.avatar_path?'<img src="'+esc(avatarUrl(p.avatar_path))+'" alt="">':'🕶️';toggle.classList.remove('hidden');toggle.textContent=active?'Envoyer sans profil':'Utiliser mon profil';edit.textContent='Modifier mon profil anonyme'}else{name.textContent='Sans profil';hint.textContent='Tu peux rester totalement anonyme ou créer un profil anonyme avec un nom et une image.';av.textContent='🕶️';toggle.classList.add('hidden');edit.textContent='Créer mon profil anonyme'}}
async function uploadAnonAvatar(file){if(!file)throw new Error('Image manquante.');var fd=new FormData();fd.append('device_id',deviceId());fd.append('file',file,file.name||'avatar.png');var res=await fetch(ANON_AVATAR_API,{method:'POST',headers:{'apikey':SUPABASE_KEY},body:fd});var out=null;try{out=await res.json()}catch(e){}if(!res.ok||!out||!out.path)throw new Error((out&&out.error)||'Impossible d’enregistrer l’image.');return out}
function generatedAnonName(){var names=['Nova','Lynx','Pixel','Écho','Orion','Atlas','Moka','Sora','Nébula','Kiro','Astra','Cosmo'];return names[Math.floor(Math.random()*names.length)]+' '+String(Math.floor(100+Math.random()*900))}
function avatarBlobFor(label){return new Promise(function(resolve,reject){try{var c=document.createElement('canvas');c.width=256;c.height=256;var x=c.getContext('2d'),pal=[['#e8e3ff','#6758e8'],['#dff4fb','#268fb8'],['#e9f8ef','#32956a'],['#fff0df','#b56b28'],['#ffe8ef','#bd5676']],p=pal[Math.floor(Math.random()*pal.length)];x.fillStyle=p[0];x.fillRect(0,0,256,256);x.fillStyle=p[1];x.beginPath();x.arc(198,58,76,0,Math.PI*2);x.fill();x.globalAlpha=.20;x.beginPath();x.arc(44,218,106,0,Math.PI*2);x.fill();x.globalAlpha=1;x.fillStyle='#ffffff';x.beginPath();x.arc(128,128,74,0,Math.PI*2);x.fill();x.fillStyle=p[1];x.font='700 62px system-ui,sans-serif';x.textAlign='center';x.textBaseline='middle';var initials=String(label||'A').trim().split(/\s+/).slice(0,2).map(function(v){return v.charAt(0)}).join('').toUpperCase();x.fillText(initials||'A',128,132);c.toBlob(function(b){b?resolve(b):reject(new Error('Impossible de générer l’avatar.'))},'image/png',.92)}catch(e){reject(e)}})}
async function createGeneratedAnonProfile(){var btn=$('anonGenerateProfile');btn.disabled=true;status($('anonProfileStatus'),'Génération du profil…',true);try{var pseudo=generatedAnonName(),blob=await avatarBlobFor(pseudo),file=new File([blob],'avatar-anonyme.png',{type:'image/png'}),up=await uploadAnonAvatar(file);saveAnonProfileLocal({pseudonym:pseudo,avatar_path:up.path,enabled:true,generated:true});clearStatus($('anonProfileStatus'));showToast('Profil anonyme généré ✓',true)}catch(e){status($('anonProfileStatus'),e.message||'Impossible de générer le profil.',false)}btn.disabled=false}
async function saveAnonProfileEditor(){var pseudo=$('anonProfileNameInput').value.trim(),file=$('anonProfileImageInput').files&&$('anonProfileImageInput').files[0],current=anonLocalProfile||anonProfileStored();if(pseudo.length<2||pseudo.length>32)return status($('anonProfileStatus'),'Le nom doit contenir entre 2 et 32 caractères.',false);$('anonProfileSave').disabled=true;status($('anonProfileStatus'),'Enregistrement…',true);try{var path=current&&current.avatar_path||null;if(file){var up=await uploadAnonAvatar(file);path=up.path}else if(!path){var blob=await avatarBlobFor(pseudo),generatedFile=new File([blob],'avatar-anonyme.png',{type:'image/png'}),auto=await uploadAnonAvatar(generatedFile);path=auto.path}saveAnonProfileLocal({pseudonym:pseudo,avatar_path:path,enabled:true,generated:false});$('anonProfileEditor').classList.add('hidden');$('anonProfileImageInput').value='';clearStatus($('anonProfileStatus'));showToast('Profil anonyme enregistré ✓',true)}catch(e){status($('anonProfileStatus'),e.message||'Impossible d’enregistrer le profil.',false)}$('anonProfileSave').disabled=false}
function bindAnonProfileControls(){anonLocalProfile=anonProfileStored();var edit=$('anonEditProfile');if(!edit)return;edit.onclick=function(){var p=anonLocalProfile||anonProfileStored();$('anonProfileNameInput').value=p&&p.pseudonym||'';$('anonProfileEditor').classList.remove('hidden');$('anonProfileNameInput').focus()};$('anonProfileCancel').onclick=function(){$('anonProfileEditor').classList.add('hidden');clearStatus($('anonProfileStatus'))};$('anonProfileSave').onclick=saveAnonProfileEditor;$('anonGenerateProfile').onclick=createGeneratedAnonProfile;$('anonToggleProfile').onclick=function(){var p=anonLocalProfile||anonProfileStored();if(!p)return;p.enabled=p.enabled===false?true:false;saveAnonProfileLocal(p)};renderAnonProfilePanel()}
'''
anchor='function avatarUrl(path){'
if anchor not in html: raise SystemExit('avatarUrl anchor missing')
html=html.replace(anchor,inject+anchor,1)

old_select="function selectSendMode(m){sendMode=m;$('anonBtn').classList.toggle('active',m==='anonymous');$('profileBtn').classList.toggle('active',m==='profile');if(m==='anonymous')$('identityInfo').textContent='Ton identité ne sera pas envoyée au destinataire.';else if(session)$('identityInfo').textContent='Ton pseudonyme et ton image seront affichés avec le message.';else{$('identityInfo').innerHTML='Connecte-toi ou crée un compte pour envoyer avec ton profil. <button id=\"inlineLogin\" class=\"ghost\" style=\"margin-top:8px\">Se connecter</button>';setTimeout(function(){var b=$('inlineLogin');if(b)b.onclick=function(){goto(BASE+'?app=1&returnTo='+encodeURIComponent(location.href))}},0)}}"
new_select="function selectSendMode(m){sendMode=m;$('anonBtn').classList.toggle('active',m==='anonymous');$('profileBtn').classList.toggle('active',m==='profile');if(m==='anonymous'){$('identityInfo').textContent='Tu peux rester sans profil ou utiliser un profil anonyme local. Ton compte et ton e-mail ne sont jamais révélés.';renderAnonProfilePanel()}else{if($('anonIdentityPanel'))$('anonIdentityPanel').classList.add('hidden');if(session)$('identityInfo').textContent='Ton pseudonyme et ton image de compte seront affichés avec le message.';else{$('identityInfo').innerHTML='Connecte-toi ou crée un compte pour envoyer avec ton profil. <button id=\"inlineLogin\" class=\"ghost\" style=\"margin-top:8px\">Se connecter</button>';setTimeout(function(){var b=$('inlineLogin');if(b)b.onclick=function(){goto(BASE+'?app=1&returnTo='+encodeURIComponent(location.href))}},0)}}}"
if old_select not in html: raise SystemExit('selectSendMode block missing')
html=html.replace(old_select,new_select,1)

old_rpc="var out=await rpc('anonbox_submit_message',{p_slug:(qs.get('to')||''),p_body:text,p_mode:sendMode,p_device_id:deviceId()});"
new_rpc="var ap=sendMode==='anonymous'?anonProfilePayload():null,out=await rpc('anonbox_submit_message',{p_slug:(qs.get('to')||''),p_body:text,p_mode:sendMode,p_device_id:deviceId(),p_anon_pseudonym:ap?ap.pseudonym:null,p_anon_avatar_path:ap?ap.avatar_path:null});"
if old_rpc not in html: raise SystemExit('public submit rpc missing')
html=html.replace(old_rpc,new_rpc,1)

old_chat_rpc="var out=await rpc('anonbox_submit_message',{p_slug:c.slug,p_body:text,p_mode:threadMode,p_device_id:deviceId(),p_reply_to_id:replyTarget?replyTarget.id:null});"
new_chat_rpc="var ap=threadMode==='anonymous'?anonProfilePayload():null,out=await rpc('anonbox_submit_message',{p_slug:c.slug,p_body:text,p_mode:threadMode,p_device_id:deviceId(),p_reply_to_id:replyTarget?replyTarget.id:null,p_anon_pseudonym:ap?ap.pseudonym:null,p_anon_avatar_path:ap?ap.avatar_path:null});"
if old_chat_rpc not in html: raise SystemExit('visitor chat rpc missing')
html=html.replace(old_chat_rpc,new_chat_rpc,1)

old_fd="if(replyTarget)fd.append('reply_to_id',String(replyTarget.id));fd.append('file',file,file.name);"
new_fd="if(replyTarget)fd.append('reply_to_id',String(replyTarget.id));if(activeChatViewer==='visitor'){var ap=anonProfilePayload();if(ap){fd.append('anon_pseudonym',ap.pseudonym);if(ap.avatar_path)fd.append('anon_avatar_path',ap.avatar_path)}}fd.append('file',file,file.name);"
if old_fd not in html: raise SystemExit('attachment form anchor missing')
html=html.replace(old_fd,new_fd,1)

old_identity="function conversationIdentity(c){var visitor=c.messages.filter(function(m){return m.direction==='visitor'}),profileMode=visitor.some(function(m){return m.sender_mode==='profile'}),named=visitor.slice().reverse().find(function(m){return m.sender_mode==='profile'&&m.sender_pseudonym_snapshot}),unreadCount=visitor.filter(function(m){return !m.read_at}).length;return {profile:profileMode,name:profileMode?((named&&named.sender_pseudonym_snapshot)||'Profil'):'Anonyme',avatar:profileMode?avatarUrl(named&&named.sender_avatar_path_snapshot):null,unread:unreadCount>0,unreadCount:unreadCount}}"
new_identity="function conversationIdentity(c){var visitor=c.messages.filter(function(m){return m.direction==='visitor'}),profileMode=visitor.some(function(m){return m.sender_mode==='profile'}),named=visitor.slice().reverse().find(function(m){return m.sender_mode==='profile'&&m.sender_pseudonym_snapshot}),anonNamed=visitor.slice().reverse().find(function(m){return m.sender_mode==='anonymous'&&m.sender_pseudonym_snapshot}),unreadCount=visitor.filter(function(m){return !m.read_at}).length,anonymousProfile=!profileMode&&!!anonNamed;return {profile:profileMode,anonymousProfile:anonymousProfile,name:profileMode?((named&&named.sender_pseudonym_snapshot)||'Profil'):(anonymousProfile?anonNamed.sender_pseudonym_snapshot:'Anonyme'),avatar:profileMode?avatarUrl(named&&named.sender_avatar_path_snapshot):(anonymousProfile&&anonNamed.sender_avatar_path_snapshot?avatarUrl(anonNamed.sender_avatar_path_snapshot):null),unread:unreadCount>0,unreadCount:unreadCount}}"
if old_identity not in html: raise SystemExit('conversationIdentity missing')
html=html.replace(old_identity,new_identity,1)

html=html.replace("<span class=\"chatMode\">'+(info.profile?'👤 Profil':'🕶️ Anonyme')+'</span>","<span class=\"chatMode\">'+(info.profile?'👤 Profil':(info.anonymousProfile?'🕶️ Profil anonyme':'🕶️ Anonyme'))+'</span>",1)
html=html.replace("renderHeader(info.name,info.profile?'Profil visible':'Conversation anonyme',info.avatar,!info.profile);","renderHeader(info.name,info.profile?'Profil visible':(info.anonymousProfile?'Profil anonyme · identité réelle masquée':'Conversation anonyme'),info.avatar,!info.profile);",1)
html=html.replace("$('chatNotice').textContent=info.profile?'Cette personne a choisi volontairement d’afficher son profil.':'L’identité réelle de cet expéditeur anonyme n’est pas affichée.';","$('chatNotice').textContent=info.profile?'Cette personne a choisi volontairement d’afficher son profil de compte.':(info.anonymousProfile?'Le nom et l’image sont un profil anonyme local. Aucune identité de compte n’est révélée.':'L’identité réelle de cet expéditeur anonyme n’est pas affichée.');",1)

route_anchor="    $('landingCreate').onclick=function(){"
if route_anchor not in html: raise SystemExit('route anchor missing')
html=html.replace(route_anchor,"    bindAnonProfileControls();\n"+route_anchor,1)

css=r'''
    /* anonbox-light-ui-v6 */
    :root{--bg:#f6f8fc;--panel:#ffffff;--panel2:#eef3f8;--text:#1c2737;--muted:#6f7b8d;--line:rgba(35,48,67,.12);--brand:#6758e8;--brand2:#2d9cc2;--ok:#278660;--bad:#c74760;--surface-soft:#f7f9fc;--surface-raised:#ffffff;--shadow-soft:0 10px 30px rgba(38,52,74,.08)}
    html{color-scheme:light!important;background:#f6f8fc}
    body{background:radial-gradient(circle at 10% -10%,rgba(103,88,232,.10),transparent 32%),radial-gradient(circle at 100% 0,rgba(45,156,194,.08),transparent 28%),#f6f8fc!important;color:#1c2737!important}
    .brand{color:#4d467f}.brand i{box-shadow:0 0 14px rgba(103,88,232,.28)}
    .hero p,.muted{color:#6f7b8d!important}.tag{background:#fff;border-color:rgba(35,48,67,.10);color:#5f6c80;box-shadow:0 4px 16px rgba(38,52,74,.04)}
    .card{background:#fff!important;border-color:rgba(35,48,67,.10)!important;box-shadow:0 10px 28px rgba(38,52,74,.07)!important;color:#1c2737}
    input,textarea{background:#f9fbfd!important;color:#1c2737!important;border-color:rgba(35,48,67,.13)!important}input::placeholder,textarea::placeholder{color:#98a2b2}input:focus,textarea:focus{border-color:rgba(103,88,232,.48)!important;box-shadow:0 0 0 3px rgba(103,88,232,.09)!important}
    button.secondary{background:#eef1ff!important;border-color:#dcd8ff!important;color:#5147b3!important}button.ghost{background:#fff!important;border-color:rgba(35,48,67,.13)!important;color:#566477!important}button.danger{background:#fff1f3!important;border-color:#ffd4dc!important;color:#b53c55!important}
    .tabs{background:#eef2f7!important;border-color:rgba(35,48,67,.10)!important}.tabs button{color:#748195}.tabs button.active{background:#fff!important;color:#302967!important;box-shadow:0 3px 10px rgba(38,52,74,.07)}
    .status.ok{background:#ebf8f2!important;border-color:#bfe8d7!important;color:#256f53!important}.status.err{background:#fff0f2!important;border-color:#f7c9d1!important;color:#a9374e!important}
    .mode button,#publicView .mode button{background:#f3f5f9!important;border-color:rgba(35,48,67,.10)!important;color:#627084!important}.mode button.active,#publicView .mode button.active{background:#ece9ff!important;border-color:#d2ccff!important;color:#5045b6!important}
    #publicView .hero,#authView .hero{background:linear-gradient(145deg,#ffffff,#f3f1ff)!important;border-color:rgba(103,88,232,.11)!important;box-shadow:0 14px 34px rgba(38,52,74,.07)!important}#publicView .hero:after{background:radial-gradient(circle,rgba(103,88,232,.10),transparent 67%)!important}
    #messageBody{background:#fbfcfe!important}#publicLibrary{background:#fff!important}#publicBox>.card:not(.stack){background:#fff!important}
    .messengerTop{background:rgba(255,255,255,.94)!important;border-bottom-color:rgba(35,48,67,.08)!important;box-shadow:0 5px 18px rgba(38,52,74,.04)}.pageTitle{color:#1c2737}.topUserLine{color:#778398!important}.topAvatar{box-shadow:0 4px 14px rgba(52,62,96,.13)}.iconButton{background:#f4f6fa!important;border-color:rgba(35,48,67,.09)!important;color:#59677b!important}
    .searchBox{background:#fff!important;border-color:rgba(35,48,67,.10)!important;box-shadow:0 4px 14px rgba(38,52,74,.04)!important}.searchBox input{background:transparent!important}.filterChip{background:#fff!important;border-color:rgba(35,48,67,.10)!important;color:#687588!important}.filterChip.active{background:#ece9ff!important;border-color:#d5d0ff!important;color:#5147b3!important}
    .messengerList{background:#fff!important;box-shadow:inset 0 0 0 1px rgba(35,48,67,.07)!important}.messengerList .conversationList:not(:last-child){border-bottom-color:rgba(35,48,67,.07)!important}.chatRow:hover,.chatRow:active{background:#f7f9fc!important}.chatRow.unread{background:linear-gradient(90deg,rgba(103,88,232,.07),transparent 72%)!important}.chatRowName{color:#273244!important}.chatPreview{color:#778398!important}.chatRow.unread .chatPreview{color:#4d5a6d!important}.chatRowTime{color:#8a95a5!important}.chatMode{background:#f1f4f8!important;color:#738095!important}.msgAvatar{background:linear-gradient(145deg,#eef1f6,#e5e9f0)!important;border-color:rgba(35,48,67,.08)!important;color:#4f5f73}
    .stat{background:#fff!important;border-color:rgba(35,48,67,.09)!important}.contact{background:#fff!important;border-color:rgba(35,48,67,.10)!important}.settingGrid label{color:#3e4a5c}.logoPreview{background:#f0f3f7!important;border-color:rgba(35,48,67,.10)!important}
    .nav{background:rgba(255,255,255,.96)!important;border-color:rgba(35,48,67,.11)!important;box-shadow:0 12px 32px rgba(38,52,74,.13)!important}.nav button{color:#7a8799!important}.nav button.active{background:#eeebff!important;color:#5147b3!important;box-shadow:inset 0 0 0 1px rgba(103,88,232,.10)!important}.navBadge{box-shadow:0 0 0 2px #fff!important}
    .chatScreenShell{background:#f6f8fc!important}.chatScreenHeader{background:rgba(255,255,255,.95)!important;border-bottom-color:rgba(35,48,67,.08)!important;box-shadow:0 4px 16px rgba(38,52,74,.04)}.backBtn,.headerAction{color:#58667a!important}.headerAction{background:#f3f5f8!important;border-color:rgba(35,48,67,.09)!important}.chatHeaderName{color:#253044}.chatHeaderSub{color:#778398!important}
    .chatScreenBody{background:radial-gradient(circle at 15% 5%,rgba(103,88,232,.05),transparent 26%),radial-gradient(circle at 90% 85%,rgba(45,156,194,.04),transparent 27%),#f6f8fc!important}.dayPill{background:#fff!important;color:#7c8899!important;border:1px solid rgba(35,48,67,.08)!important}.bubble.left{background:#fff!important;color:#263142!important;border:1px solid rgba(35,48,67,.08)!important}.bubble.right{background:#e9e6ff!important;color:#302a64!important;border:1px solid #ddd8ff!important}.bubbleMeta,.bubble.left .bubbleMeta{color:#8590a0!important}.readMark{color:#3f88b7!important}.replyQuote{background:rgba(255,255,255,.58)!important;color:#5c687b!important;border-left-color:#796be9!important}.reactionPill{background:#fff!important;border-color:rgba(35,48,67,.10)!important;color:#425064}
    .chatComposer{background:linear-gradient(180deg,rgba(246,248,252,0),rgba(246,248,252,.94) 22%,#f6f8fc)!important}.chatComposer textarea{background:#fff!important;border-color:rgba(35,48,67,.11)!important;box-shadow:0 5px 16px rgba(38,52,74,.08)!important}.attachButton{background:#fff!important;border-color:rgba(35,48,67,.11)!important;color:#657286!important}.sendCircle{background:#6758e8!important;box-shadow:0 5px 15px rgba(103,88,232,.22)!important}.replyComposerBar{background:#fff!important;border-left-color:#6758e8!important;box-shadow:0 4px 14px rgba(38,52,74,.06)}
    .actionBackdrop{background:rgba(45,55,72,.28)!important}.actionSheet{background:#fff!important;border-color:rgba(35,48,67,.10)!important;box-shadow:0 -18px 50px rgba(38,52,74,.16)!important}.actionPreview,.reactionPicker button,.actionGrid button,.forwardTarget{background:#f7f9fc!important;border-color:rgba(35,48,67,.10)!important;color:#425064!important}.actionHandle{background:#c8cfda!important}.conversationMenuInfo{background:#f7f9fc!important;color:#59667a!important}.attachmentCard{background:rgba(255,255,255,.66)!important;border-color:rgba(35,48,67,.09)!important;color:#344155!important}
    .librarySummary{color:#748195!important}.empty{color:#748195!important}.footer{color:#8b96a6!important}
    .unreadDivider{color:#5b50c8!important}.unreadDivider:before,.unreadDivider:after{background:rgba(103,88,232,.18)!important}.chatScrollToBottom{background:#fff!important;color:#5d6a7e!important;border-color:rgba(35,48,67,.11)!important;box-shadow:0 8px 25px rgba(38,52,74,.12)!important}
    .anonIdentityPanel{display:grid;gap:11px;padding:13px;border:1px solid rgba(103,88,232,.13);border-radius:18px;background:linear-gradient(145deg,#faf9ff,#f4f8fc)}.anonIdentityCurrent{display:flex;align-items:center;gap:11px}.anonProfileAvatar{width:50px;height:50px;flex:0 0 50px;border-radius:50%;display:grid;place-items:center;overflow:hidden;background:#ece9ff;border:1px solid #dcd7ff;font-size:21px}.anonProfileAvatar img{width:100%;height:100%;object-fit:cover}.anonProfileSummary{display:grid;gap:3px;min-width:0}.anonProfileSummary b{font-size:14px;color:#2f3950}.anonProfileSummary span{font-size:11px;color:#738095;line-height:1.35}.anonIdentityActions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.anonIdentityActions button{min-height:40px;padding:9px 10px;font-size:11px}.anonIdentityActions #anonToggleProfile{grid-column:1/-1}.anonProfileEditor{display:grid;gap:9px;padding-top:4px}.anonProfileEditor label{display:grid;gap:5px;font-size:11px;font-weight:700;color:#536176}.anonEditorActions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.anonProfileEditor input{min-height:42px}.anonProfileEditor input[type=file]{padding:9px;background:#fff!important}
    @media(max-width:520px){.anonIdentityActions{grid-template-columns:1fr}.anonIdentityActions #anonToggleProfile{grid-column:auto}.anonEditorActions{grid-template-columns:1fr}}
'''
if '</style>' not in html: raise SystemExit('style close missing')
html=html.replace('</style>',css+'\n  </style>',1)

INDEX.write_text(html,encoding='utf-8')

sw=SW.read_text(encoding='utf-8')
sw=sw.replace("const CACHE='anonbox-v13';","const CACHE='anonbox-v14';")
SW.write_text(sw,encoding='utf-8')
VERSION.write_text('AnonBox web UI v6\nLight interface by default\nAnonymous visitors: no profile, custom local anonymous profile, or generated anonymous profile with image\nAnonymous account identity remains hidden\nCache: anonbox-v14\n',encoding='utf-8')
print('anonymous profiles + light UI v6 applied')
