from pathlib import Path
import re

INDEX=Path('web/index.html')
SW=Path('web/sw.js')
VERSION=Path('web/version.txt')
html=INDEX.read_text(encoding='utf-8')
MARK='/* anonbox-voice-view-once-v8 */'
if MARK in html:
    raise SystemExit(0)

html=html.replace("ATTACHMENT_API=SUPABASE_URL+'/functions/v1/anonbox-attachment',ANON_AVATAR_API=", "ATTACHMENT_API=SUPABASE_URL+'/functions/v1/anonbox-attachment',VIEW_ONCE_API=SUPABASE_URL+'/functions/v1/anonbox-view-once',ANON_AVATAR_API=",1)
html=html.replace("composerCounter=null,anonLocalProfile=null;", "composerCounter=null,anonLocalProfile=null,viewOnceNext=false,publicViewOnce=false,voiceRecorder=null,voiceStream=null,voiceChunks=[],voiceStartedAt=0,voiceTimer=null,voiceBlob=null,voiceMime='',voiceDurationMs=0,voiceContext='chat';",1)

css=r'''
    /* anonbox-voice-view-once-v8 */
    .voiceMessage{display:grid;gap:5px;min-width:210px}.voiceAudio{width:min(270px,70vw);height:38px}.voiceDuration{font-size:9px;opacity:.72}.voiceRecordBtn.recording{animation:voicePulse 1.05s infinite}.viewOnceToggle.active{outline:2px solid rgba(108,91,225,.5);font-weight:900}.viewOnceCard{display:grid;gap:5px;padding:9px 10px;border-radius:13px;border:1px dashed currentColor;opacity:.94}.viewOnceCard button{width:100%;padding:9px 11px;border-radius:11px;background:rgba(95,105,125,.12);color:inherit;border:1px solid rgba(70,80,96,.12)}.viewOnceHint{font-size:9px;opacity:.72}.viewOnceOpened{display:flex;align-items:center;gap:7px;font-size:12px;opacity:.72}.viewOnceBackdrop{position:fixed;inset:0;z-index:160;background:rgba(17,25,31,.74);display:flex;align-items:center;justify-content:center;padding:18px}.viewOnceViewer{width:min(100%,520px);max-height:88vh;overflow:auto;border-radius:24px;padding:18px;background:var(--panel,#d9e3e2);color:var(--text,#24363b);box-shadow:0 22px 70px rgba(0,0,0,.32)}.viewOnceViewer h3{margin:0 0 5px}.viewOnceViewer p{white-space:pre-wrap;line-height:1.55}.viewOnceViewer img{display:block;max-width:100%;max-height:58vh;margin:10px auto;border-radius:16px}.viewOnceViewer audio{width:100%;margin:10px 0}.viewOnceViewer .viewOnceNotice{font-size:10px;opacity:.7;margin-bottom:12px}.viewOnceViewerClose{width:100%;margin-top:14px}.voiceBackdrop{position:fixed;inset:0;z-index:155;background:rgba(20,31,35,.46);display:flex;align-items:flex-end;justify-content:center;padding:12px}.voicePanel{width:min(100%,520px);border-radius:24px;padding:15px;background:var(--panel,#d9e3e2);color:var(--text,#24363b);box-shadow:0 -18px 55px rgba(20,32,38,.22)}.voiceRecordingLine{display:flex;align-items:center;gap:10px;padding:10px 3px}.voiceDot{width:12px;height:12px;border-radius:50%;background:#d84a61;animation:voicePulse 1s infinite}.voiceTimerText{font-weight:900;font-variant-numeric:tabular-nums}.voicePreview{width:100%;margin:8px 0}.voiceActions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.voiceActions.three{grid-template-columns:1fr 1fr 1fr}.publicMessageTools{display:grid;grid-template-columns:1fr 1fr;gap:8px}.publicMessageTools button{min-height:42px}.viewOnceWarning{font-size:10px;line-height:1.4;opacity:.72}
    @keyframes voicePulse{0%,100%{transform:scale(1);opacity:1}50%{transform:scale(1.14);opacity:.58}}
'''
html=html.replace('</style>',css+'\n  </style>',1)

# realtime view-once events
html=html.replace(".on('broadcast',{event:'reaction'},function(){scheduleLibraryReload()}).subscribe()", ".on('broadcast',{event:'reaction'},function(){scheduleLibraryReload()}).on('broadcast',{event:'view_once'},function(){scheduleLibraryReload()}).subscribe()",1)
html=html.replace(".on('broadcast',{event:'reaction'},function(){activeChatReload()}).on('broadcast',{event:'typing'},showRemoteTyping)", ".on('broadcast',{event:'reaction'},function(){activeChatReload()}).on('broadcast',{event:'view_once'},function(){activeChatReload()}).on('broadcast',{event:'typing'},showRemoteTyping)",1)

# richer attachment renderer with inline voice player
old_attach="function attachmentHtml(m){if(!m||!m.attachment_id)return '';var image=String(m.attachment_mime||'').indexOf('image/')===0,visual=image?'<span class=\"attachmentThumb\" data-attachment-thumb=\"'+esc(m.id)+'\">🖼️</span>':'<span class=\"attachmentThumb\">'+attachmentIcon(m.attachment_mime)+'</span>';return '<button type=\"button\" class=\"attachmentCard attachmentOpen\" data-attachment-message=\"'+esc(m.id)+'\">'+visual+'<span class=\"attachmentInfo\"><span class=\"attachmentName\">'+esc(m.attachment_name||'Fichier')+'</span><span class=\"attachmentMeta\">'+esc(attachmentSize(m.attachment_size))+' · ouvrir</span></span></button>'}"
new_attach="function formatVoiceDuration(ms){ms=Number(ms||0);var s=Math.max(0,Math.round(ms/1000)),m=Math.floor(s/60);return m+':'+String(s%60).padStart(2,'0')}function attachmentHtml(m){if(!m||!m.attachment_id)return '';var mime=String(m.attachment_mime||''),audio=mime.indexOf('audio/')===0,image=mime.indexOf('image/')===0;if(audio)return '<div class=\"voiceMessage\"><audio class=\"voiceAudio\" controls preload=\"metadata\" controlsList=\"nodownload\" data-voice-message=\"'+esc(m.id)+'\"></audio><span class=\"voiceDuration\">🎤 '+esc(formatVoiceDuration(m.voice_duration_ms))+'</span></div>';var visual=image?'<span class=\"attachmentThumb\" data-attachment-thumb=\"'+esc(m.id)+'\">🖼️</span>':'<span class=\"attachmentThumb\">'+attachmentIcon(m.attachment_mime)+'</span>';return '<button type=\"button\" class=\"attachmentCard attachmentOpen\" data-attachment-message=\"'+esc(m.id)+'\">'+visual+'<span class=\"attachmentInfo\"><span class=\"attachmentName\">'+esc(m.attachment_name||'Fichier')+'</span><span class=\"attachmentMeta\">'+esc(attachmentSize(m.attachment_size))+' · ouvrir</span></span></button>'}"
if old_attach not in html: raise SystemExit('attachmentHtml anchor missing')
html=html.replace(old_attach,new_attach,1)

old_bind="function bindAttachmentCards(){document.querySelectorAll('.attachmentOpen').forEach(function(el){el.onclick=function(e){e.stopPropagation();openAttachment(el.getAttribute('data-attachment-message'))}});document.querySelectorAll('[data-attachment-thumb]').forEach(function(el){var id=el.getAttribute('data-attachment-thumb');signedAttachmentUrl(id).then(function(url){if(document.body.contains(el))el.innerHTML='<img src=\"'+esc(url)+'\" alt=\"\">'}).catch(function(){})})}"
new_bind="function bindAttachmentCards(){document.querySelectorAll('.attachmentOpen').forEach(function(el){el.onclick=function(e){e.stopPropagation();openAttachment(el.getAttribute('data-attachment-message'))}});document.querySelectorAll('[data-attachment-thumb]').forEach(function(el){var id=el.getAttribute('data-attachment-thumb');signedAttachmentUrl(id).then(function(url){if(document.body.contains(el))el.innerHTML='<img src=\"'+esc(url)+'\" alt=\"\">'}).catch(function(){})});document.querySelectorAll('[data-voice-message]').forEach(function(el){var id=el.getAttribute('data-voice-message');signedAttachmentUrl(id).then(function(url){if(document.body.contains(el))el.src=url}).catch(function(){el.outerHTML='<span class=\"small muted\">Vocal indisponible</span>'})})}"
if old_bind not in html: raise SystemExit('bindAttachmentCards anchor missing')
html=html.replace(old_bind,new_bind,1)

# replace uploadAttachment function
pattern=r"async function uploadAttachment\(file\)\{.*?\}\nasync function signedAttachmentUrl"
replacement="""async function uploadAttachment(file,opts){opts=opts||{};if(attachmentBusy||!chatId)return false;if(file.size>10485760){alert('Fichier trop volumineux : 10 Mo maximum.');return false}attachmentBusy=true;var btn=$('chatAttachmentBtn');if(btn)btn.disabled=true;status($('chatScreenStatus'),opts.voice?'Envoi du vocal…':'Envoi du fichier…',true);try{var fd=new FormData();fd.append('conversation_id',chatId);fd.append('device_id',deviceId());fd.append('caption',$('chatInput').value.trim());if(replyTarget)fd.append('reply_to_id',String(replyTarget.id));if(activeChatViewer==='visitor'){var ap=anonProfilePayload();if(ap){fd.append('anon_pseudonym',ap.pseudonym);if(ap.avatar_path)fd.append('anon_avatar_path',ap.avatar_path)}}fd.append('view_once',String(opts.view_once!=null?!!opts.view_once:!!viewOnceNext));if(opts.voice_duration_ms)fd.append('voice_duration_ms',String(opts.voice_duration_ms));fd.append('file',file,file.name);var res=await fetch(ATTACHMENT_API,{method:'POST',headers:attachmentHeaders(false),body:fd});var out=null;try{out=await res.json()}catch(e){}if(!res.ok||!out||out.ok===false)throw new Error((out&&out.error)||'Envoi impossible.');$('chatInput').value='';autoGrowComposer();updateComposerState();clearReplyTarget();viewOnceNext=false;refreshViewOnceButtons();status($('chatScreenStatus'),opts.voice?'Vocal envoyé ✓':'Fichier envoyé ✓',true);setTimeout(function(){clearStatus($('chatScreenStatus'))},1800);if(activeChatViewer==='owner')await loadAll();else await loadLibrary(true);attachmentBusy=false;if(btn)btn.disabled=false;return true}catch(e){status($('chatScreenStatus'),e.message||'Envoi impossible.',false);attachmentBusy=false;if(btn)btn.disabled=false;return false}}
async function signedAttachmentUrl"""
html,n=re.subn(pattern,replacement,html,count=1,flags=re.S)
if n!=1: raise SystemExit('uploadAttachment function patch failed')

# voice + view-once helpers before rpc
anchor="async function rpc(name,args){"
helpers=r'''function preferredVoiceMime(){if(!window.MediaRecorder)return '';var types=['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus','audio/ogg'];for(var i=0;i<types.length;i++){try{if(MediaRecorder.isTypeSupported(types[i]))return types[i]}catch(e){}}return ''}
function ensureVoicePanel(){if($('voiceBackdrop'))return;var d=document.createElement('div');d.id='voiceBackdrop';d.className='voiceBackdrop hidden';d.innerHTML='<div class="voicePanel"><div id="voiceRecordState" class="voiceRecordingLine"><span class="voiceDot"></span><span id="voiceStateLabel">Enregistrement…</span><span id="voiceTimerText" class="voiceTimerText">0:00</span></div><audio id="voicePreview" class="voicePreview hidden" controls controlsList="nodownload"></audio><div id="voiceRecordActions" class="voiceActions"><button id="voiceCancel" type="button" class="ghost">Annuler</button><button id="voiceStop" type="button" class="secondary">■ Arrêter</button></div><div id="voicePreviewActions" class="voiceActions hidden"><button id="voiceDelete" type="button" class="ghost">Supprimer</button><button id="voiceSend" type="button">Envoyer</button></div><div class="viewOnceWarning">Le micro n’est utilisé que pendant l’enregistrement. Maximum : 5 minutes / 10 Mo.</div></div>';document.body.appendChild(d);$('voiceCancel').onclick=function(){cancelVoiceRecording()};$('voiceStop').onclick=function(){stopVoiceRecording(false)};$('voiceDelete').onclick=function(){clearVoicePreview()};$('voiceSend').onclick=function(){sendRecordedVoice()};d.onclick=function(e){if(e.target===d&&voiceRecorder&&voiceRecorder.state==='inactive')clearVoicePreview()}}
function voiceTimeLabel(ms){var s=Math.max(0,Math.floor(ms/1000));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}
function updateVoiceTimer(){if(!voiceStartedAt)return;var ms=Date.now()-voiceStartedAt;$('voiceTimerText').textContent=voiceTimeLabel(ms);if(ms>=300000)stopVoiceRecording(false)}
async function beginVoiceRecording(context){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia||!window.MediaRecorder){alert('L’enregistrement vocal n’est pas disponible sur ce navigateur.');return}if(voiceRecorder&&voiceRecorder.state==='recording')return;ensureVoicePanel();voiceContext=context||'chat';voiceChunks=[];voiceBlob=null;voiceDurationMs=0;try{voiceStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});var mime=preferredVoiceMime(),opts=mime?{mimeType:mime}:undefined;voiceRecorder=new MediaRecorder(voiceStream,opts);voiceMime=voiceRecorder.mimeType||mime||'audio/webm';voiceRecorder.ondataavailable=function(e){if(e.data&&e.data.size)voiceChunks.push(e.data)};voiceRecorder.onstop=function(){voiceDurationMs=Math.min(300000,Date.now()-voiceStartedAt);if(voiceTimer){clearInterval(voiceTimer);voiceTimer=null}if(voiceStream){voiceStream.getTracks().forEach(function(t){t.stop()});voiceStream=null}voiceBlob=new Blob(voiceChunks,{type:voiceMime});var url=URL.createObjectURL(voiceBlob);$('voicePreview').src=url;$('voicePreview').classList.remove('hidden');$('voiceRecordState').classList.add('hidden');$('voiceRecordActions').classList.add('hidden');$('voicePreviewActions').classList.remove('hidden')};voiceRecorder.start(250);voiceStartedAt=Date.now();$('voiceBackdrop').classList.remove('hidden');$('voicePreview').classList.add('hidden');$('voiceRecordState').classList.remove('hidden');$('voiceRecordActions').classList.remove('hidden');$('voicePreviewActions').classList.add('hidden');$('voiceTimerText').textContent='0:00';voiceTimer=setInterval(updateVoiceTimer,250)}catch(e){if(voiceStream){voiceStream.getTracks().forEach(function(t){t.stop()});voiceStream=null}alert((e&&e.name==='NotAllowedError')?'Autorise le micro pour envoyer un message vocal.':'Impossible d’utiliser le micro.') }}
function stopVoiceRecording(cancel){if(!voiceRecorder)return;if(cancel){try{voiceRecorder.onstop=null;if(voiceRecorder.state!=='inactive')voiceRecorder.stop()}catch(e){}if(voiceStream)voiceStream.getTracks().forEach(function(t){t.stop()});if(voiceTimer)clearInterval(voiceTimer);voiceTimer=null;voiceRecorder=null;voiceStream=null;voiceChunks=[];voiceBlob=null;voiceStartedAt=0;$('voiceBackdrop').classList.add('hidden');return}if(voiceRecorder.state==='recording')voiceRecorder.stop()}
function cancelVoiceRecording(){stopVoiceRecording(true)}
function clearVoicePreview(){if(voiceRecorder&&voiceRecorder.state==='recording'){cancelVoiceRecording();return}voiceRecorder=null;voiceChunks=[];voiceBlob=null;voiceStartedAt=0;voiceDurationMs=0;var a=$('voicePreview');if(a&&a.src){try{URL.revokeObjectURL(a.src)}catch(e){}a.removeAttribute('src')}if($('voiceBackdrop'))$('voiceBackdrop').classList.add('hidden')}
async function sendRecordedVoice(){if(!voiceBlob)return;var ext=voiceMime.indexOf('ogg')>=0?'ogg':'webm',file=new File([voiceBlob],'vocal-'+Date.now()+'.'+ext,{type:voiceMime}),ok=false;$('voiceSend').disabled=true;if(voiceContext==='public')ok=await uploadPublicVoice(file,voiceDurationMs);else ok=await uploadAttachment(file,{voice:true,voice_duration_ms:voiceDurationMs,view_once:viewOnceNext});$('voiceSend').disabled=false;if(ok)clearVoicePreview()}
function ensureVoiceControls(){var composer=$('chatComposer');if(!composer)return;if(!$('chatVoiceBtn')){var mic=document.createElement('button');mic.id='chatVoiceBtn';mic.type='button';mic.className='attachButton voiceRecordBtn';mic.textContent='🎤';mic.title='Message vocal';composer.insertBefore(mic,$('chatInput'));mic.onclick=function(){beginVoiceRecording('chat')}}if(!$('chatViewOnceBtn')){var one=document.createElement('button');one.id='chatViewOnceBtn';one.type='button';one.className='attachButton viewOnceToggle';one.textContent='①';one.title='Envoyer à vue unique';composer.insertBefore(one,$('chatInput'));one.onclick=function(){viewOnceNext=!viewOnceNext;refreshViewOnceButtons()}}refreshViewOnceButtons()}
function refreshViewOnceButtons(){var c=$('chatViewOnceBtn');if(c){c.classList.toggle('active',!!viewOnceNext);c.title=viewOnceNext?'Vue unique activée':'Envoyer à vue unique'}var p=$('publicViewOnceBtn');if(p){p.classList.toggle('active',!!publicViewOnce);p.textContent=publicViewOnce?'① Vue unique activée':'① Vue unique'}}
function ensurePublicVoiceControls(){if($('publicMessageTools'))return;var send=$('sendBtn');if(!send)return;var row=document.createElement('div');row.id='publicMessageTools';row.className='publicMessageTools';row.innerHTML='<button id="publicVoiceBtn" type="button" class="secondary">🎤 Vocal</button><button id="publicViewOnceBtn" type="button" class="ghost viewOnceToggle">① Vue unique</button>';send.parentNode.insertBefore(row,send);$('publicVoiceBtn').onclick=function(){if(sendMode==='profile'&&!session){selectSendMode('profile');return}beginVoiceRecording('public')};$('publicViewOnceBtn').onclick=function(){publicViewOnce=!publicViewOnce;refreshViewOnceButtons()};refreshViewOnceButtons()}
async function uploadPublicVoice(file,duration){status($('sendStatus'),'Envoi du vocal…',true);try{var fd=new FormData(),ap=sendMode==='anonymous'?anonProfilePayload():null;fd.append('slug',(qs.get('to')||''));fd.append('mode',sendMode);fd.append('device_id',deviceId());fd.append('caption','');fd.append('view_once',String(!!publicViewOnce));fd.append('voice_duration_ms',String(duration||0));if(ap){fd.append('anon_pseudonym',ap.pseudonym);if(ap.avatar_path)fd.append('anon_avatar_path',ap.avatar_path)}fd.append('file',file,file.name);var res=await fetch(ATTACHMENT_API,{method:'POST',headers:attachmentHeaders(false),body:fd}),out=null;try{out=await res.json()}catch(e){}if(!res.ok||!out||out.ok===false)throw new Error((out&&out.error)||'Envoi du vocal impossible.');publicViewOnce=false;refreshViewOnceButtons();status($('sendStatus'),'Vocal envoyé ✓ Tu peux suivre la réponse dans « Mes conversations ».',true);return true}catch(e){status($('sendStatus'),e.message||'Envoi du vocal impossible.',false);return false}}
function isViewOnceRecipient(m,viewer){return viewer==='owner'?m.direction==='visitor':m.direction==='owner'}
function viewOnceHtml(m,viewer){if(m.view_once_opened_at)return '<div class="viewOnceOpened">① <span>Message ouvert</span></div>';if(isViewOnceRecipient(m,viewer))return '<div class="viewOnceCard"><button type="button" class="viewOnceOpen" data-view-once-message="'+esc(m.id)+'">① Voir une fois</button><span class="viewOnceHint">Après ouverture, ce contenu ne pourra plus être rouvert dans AnonBox.</span></div>';return '<div class="viewOnceCard"><b>① Message à vue unique</b><span class="viewOnceHint">En attente d’ouverture par le destinataire.</span></div>'}
function ensureViewOnceViewer(){if($('viewOnceBackdrop'))return;var d=document.createElement('div');d.id='viewOnceBackdrop';d.className='viewOnceBackdrop hidden';d.innerHTML='<div class="viewOnceViewer"><h3>① Vue unique</h3><div class="viewOnceNotice">Ce contenu ne pourra plus être rouvert dans AnonBox après fermeture. Une capture ou un enregistrement externe reste possible.</div><div id="viewOnceContent"></div><button id="viewOnceClose" type="button" class="viewOnceViewerClose">Fermer</button></div>';document.body.appendChild(d);$('viewOnceClose').onclick=function(){d.classList.add('hidden');if(activeChatViewer==='owner')loadAll();else loadLibrary(true)}}
async function openViewOnceMessage(messageId){ensureViewOnceViewer();var headers={'apikey':SUPABASE_KEY,'Content-Type':'application/json'};if(session&&session.access_token)headers.Authorization='Bearer '+session.access_token;try{var res=await fetch(VIEW_ONCE_API,{method:'POST',headers:headers,body:JSON.stringify({message_id:String(messageId),device_id:deviceId()})}),out=null;try{out=await res.json()}catch(e){}if(!res.ok||!out||out.ok===false)throw new Error((out&&out.error)||'Ouverture impossible.');var content='',a=out.attachment;if(a&&String(a.mime||'').indexOf('audio/')===0&&a.signed_url){content+='<audio controls autoplay controlsList="nodownload" src="'+esc(a.signed_url)+'"></audio>'}else if(a&&String(a.mime||'').indexOf('image/')===0&&a.signed_url){content+='<img src="'+esc(a.signed_url)+'" alt="Contenu à vue unique">'}else if(a&&a.signed_url){content+='<p>📎 '+esc(a.name||'Fichier')+'</p><button type="button" id="viewOnceFileOpen">Ouvrir le fichier</button>'}if(out.body&&!(a&&String(out.body).indexOf('🎤 Message vocal')===0))content+='<p>'+esc(out.body)+'</p>';$('viewOnceContent').innerHTML=content||'<p>Contenu ouvert.</p>';if(a&&a.signed_url&&$('viewOnceFileOpen'))$('viewOnceFileOpen').onclick=function(){location.href=a.signed_url};$('viewOnceBackdrop').classList.remove('hidden');var m=findActiveMessage(messageId);if(m)m.view_once_opened_at=out.opened_at||new Date().toISOString()}catch(e){alert(e.message||'Ce message ne peut plus être ouvert.');if(activeChatViewer==='owner')loadAll();else loadLibrary(true)}}
function bindViewOnceCards(){document.querySelectorAll('.viewOnceOpen').forEach(function(b){b.onclick=function(e){e.stopPropagation();openViewOnceMessage(b.getAttribute('data-view-once-message'))}})}
'''
if anchor not in html: raise SystemExit('rpc anchor missing')
html=html.replace(anchor,helpers+'\n'+anchor,1)

# render view-once placeholder instead of hidden payload
pattern=r"function renderMessageBubble\(m,viewer\)\{.*?\}function renderMessageStream"
new_render="""function renderMessageBubble(m,viewer){var right=viewer==='owner'?m.direction==='owner':m.direction==='visitor',readState='',src=m.reply_to_id?findActiveMessage(m.reply_to_id):null,quote=m.reply_to_id?'<div class=\"replyQuote\" data-reply-id=\"'+esc(m.reply_to_id)+'\">↪ '+esc(src?previewText(src.body):'Message indisponible')+'</div>':'',reactions=reactionHtml(m.reaction_summary),attachment=m.view_once?'':attachmentHtml(m),hideFallback=!!(m.attachment_id&&String(m.body||'')==='📎 '+String(m.attachment_name||'')),bodyPart=m.view_once?viewOnceHtml(m,viewer):(hideFallback?'':'<div class=\"bubbleText\">'+esc(m.body)+'</div>');if(right)readState=m.read_at?'<span class=\"readMark\" title=\"Lu\">✓✓</span>':'<span class=\"sentMark\" title=\"Envoyé\">✓</span>';return '<div class=\"bubble messageBubble '+(m.view_once?'viewOnceBubble ':'')+(right?'right':'left')+'\" data-message-id=\"'+esc(m.id)+'\" '+(m.view_once?'data-view-once=\"1\"':'')+'>'+quote+bodyPart+attachment+(reactions&&!m.view_once?'<div class=\"reactionStrip\">'+reactions+'</div>':'')+'<span class=\"bubbleMeta\"><span>'+esc(clockLabel(m.created_at))+'</span>'+readState+'</span></div>'}function renderMessageStream"""
html,n=re.subn(pattern,new_render,html,count=1,flags=re.S)
if n!=1: raise SystemExit('renderMessageBubble patch failed')

# add voice/view-once binds to stream
html=html.replace("ensureReplyBar();ensureAttachmentControls();ensureComposerCounter();bindMessageActions(viewer);bindReplyQuoteLinks();bindAttachmentCards();bindChatScrollTracking();", "ensureReplyBar();ensureAttachmentControls();ensureVoiceControls();ensureComposerCounter();bindMessageActions(viewer);bindReplyQuoteLinks();bindAttachmentCards();bindViewOnceCards();bindChatScrollTracking();",1)

# prevent action sheet/swipe from opening hidden view-once content
html=html.replace("document.querySelectorAll('.messageBubble').forEach(function(el){el.onclick=function(){if(el.dataset.justSwiped==='1')return;", "document.querySelectorAll('.messageBubble').forEach(function(el){el.onclick=function(){if(el.getAttribute('data-view-once')==='1'||el.dataset.justSwiped==='1')return;",1)
html=html.replace("function bindSwipeReply(viewer){document.querySelectorAll('.messageBubble').forEach(function(el){if(el.dataset.swipeBound==='1')return;", "function bindSwipeReply(viewer){document.querySelectorAll('.messageBubble').forEach(function(el){if(el.getAttribute('data-view-once')==='1'||el.dataset.swipeBound==='1')return;",1)

# public controls + p_view_once
html=html.replace("if(!data.allow_anonymous&&data.allow_profile_messages)selectSendMode('profile')", "if(!data.allow_anonymous&&data.allow_profile_messages)selectSendMode('profile');ensurePublicVoiceControls()",1)
html=html.replace("p_anon_avatar_path:ap?ap.avatar_path:null});if(!out||out.ok===false)", "p_anon_avatar_path:ap?ap.avatar_path:null,p_view_once:!!publicViewOnce});if(!out||out.ok===false)",1)
html=html.replace("$('messageBody').value='';$('count').textContent='0';status($('sendStatus')", "$('messageBody').value='';$('count').textContent='0';publicViewOnce=false;refreshViewOnceButtons();status($('sendStatus')",1)

# visitor chat p_view_once and reset
old="p_anon_pseudonym:ap?ap.pseudonym:null,p_anon_avatar_path:ap?ap.avatar_path:null});if(!out||out.ok===false)throw new Error((out&&out.error)||'Envoi impossible.');$('chatInput').value='';"
new="p_anon_pseudonym:ap?ap.pseudonym:null,p_anon_avatar_path:ap?ap.avatar_path:null,p_view_once:!!viewOnceNext});if(!out||out.ok===false)throw new Error((out&&out.error)||'Envoi impossible.');$('chatInput').value='';viewOnceNext=false;refreshViewOnceButtons();"
if old not in html: raise SystemExit('visitor send anchor missing')
html=html.replace(old,new,1)

# owner chat p_view_once and reset
old="p_conversation_id:chatId,p_body:text,p_reply_to_id:replyTarget?replyTarget.id:null});if(!out||out.ok===false)throw new Error((out&&out.error)||'Réponse impossible.');$('chatInput').value='';"
new="p_conversation_id:chatId,p_body:text,p_reply_to_id:replyTarget?replyTarget.id:null,p_view_once:!!viewOnceNext});if(!out||out.ok===false)throw new Error((out&&out.error)||'Réponse impossible.');$('chatInput').value='';viewOnceNext=false;refreshViewOnceButtons();"
if old not in html: raise SystemExit('owner send anchor missing')
html=html.replace(old,new,1)

# owner selects new metadata
html=html.replace("attachment_id,attachment_name,attachment_mime,attachment_size').is('deleted_at'", "attachment_id,attachment_name,attachment_mime,attachment_size,view_once,view_once_opened_at,voice_duration_ms').is('deleted_at'",1)

# attachment chooser supports recorded audio formats too
html=html.replace("audio/mpeg,audio/mp4,video/mp4", "audio/mpeg,audio/mp4,audio/webm,audio/ogg,video/mp4",1)

# cache/version
INDEX.write_text(html,encoding='utf-8')
sw=SW.read_text(encoding='utf-8').replace("const CACHE='anonbox-v18';","const CACHE='anonbox-v19';")
SW.write_text(sw,encoding='utf-8')
VERSION.write_text('AnonBox web UI v8\nVoice messages with recording and inline playback\nView-once text and attachments with recipient-only one-time opening\n13 selectable themes preserved\nCache: anonbox-v19\n',encoding='utf-8')
print('voice + view once v8 applied')
