from pathlib import Path

INDEX=Path('web/index.html')
SW=Path('web/sw.js')
VERSION=Path('web/version.txt')
html=INDEX.read_text(encoding='utf-8')
MARK='/* anonbox-theme-selector-v7 */'
if MARK in html:
    raise SystemExit(0)

html=html.replace('<meta name="theme-color" content="#e9eef5">','<meta name="theme-color" content="#cad8d8">',1)

head_script='''<script>(function(){try{var t=localStorage.getItem('anonbox_theme_v1')||'mix';document.documentElement.setAttribute('data-anon-theme',t);document.documentElement.style.colorScheme=t==='night'?'dark':'light'}catch(e){document.documentElement.setAttribute('data-anon-theme','mix')}})();</script>'''
html=html.replace('<title>AnonBox</title>','<title>AnonBox</title>\n  '+head_script,1)

css=r'''
    /* anonbox-theme-selector-v7 */
    html[data-anon-theme="mix"]{background:#cad8d8!important;color-scheme:light}
    html[data-anon-theme="mix"] body{background:radial-gradient(circle at 7% -5%,rgba(70,116,148,.18),transparent 30%),radial-gradient(circle at 98% 0,rgba(79,132,101,.16),transparent 28%),#cad8d8!important;color:#213039!important}
    html[data-anon-theme="mix"] .card{background:#dce6e4!important;border-color:rgba(40,66,70,.16)!important;box-shadow:0 9px 24px rgba(42,62,68,.09)!important}
    html[data-anon-theme="mix"] .tag,html[data-anon-theme="mix"] .stat,html[data-anon-theme="mix"] .contact,html[data-anon-theme="mix"] .messengerList,html[data-anon-theme="mix"] #publicLibrary,html[data-anon-theme="mix"] #publicBox>.card:not(.stack){background:#d5e0df!important;border-color:rgba(40,66,70,.14)!important}
    html[data-anon-theme="mix"] input,html[data-anon-theme="mix"] textarea,html[data-anon-theme="mix"] #messageBody{background:#cfdbdc!important;color:#213039!important;border-color:rgba(40,66,70,.17)!important}
    html[data-anon-theme="mix"] button.secondary{background:#c4d6db!important;border-color:#a9c3cc!important;color:#315c6b!important}html[data-anon-theme="mix"] button.ghost{background:#d2dddc!important;border-color:rgba(40,66,70,.15)!important;color:#405b63!important}
    html[data-anon-theme="mix"] #publicView .hero,html[data-anon-theme="mix"] #authView .hero{background:linear-gradient(145deg,#d4e0e3,#d7e4dc)!important;border-color:rgba(59,103,104,.17)!important}
    html[data-anon-theme="mix"] .anonIdentityPanel{background:linear-gradient(145deg,#cbdadd,#d5e2d8)!important;border-color:rgba(62,112,111,.19)!important}
    html[data-anon-theme="mix"] .messengerTop,html[data-anon-theme="mix"] .chatScreenHeader{background:rgba(202,216,216,.97)!important;border-color:rgba(40,66,70,.14)!important}
    html[data-anon-theme="mix"] .iconButton,html[data-anon-theme="mix"] .searchBox,html[data-anon-theme="mix"] .filterChip,html[data-anon-theme="mix"] .headerAction{background:#c5d3d4!important;border-color:rgba(40,66,70,.14)!important;color:#40565e!important}
    html[data-anon-theme="mix"] .filterChip.active{background:#b9ced0!important;border-color:#94b8bd!important;color:#285c67!important}
    html[data-anon-theme="mix"] .nav{background:rgba(194,210,211,.98)!important;border-color:rgba(40,66,70,.16)!important}html[data-anon-theme="mix"] .nav button.active{background:#afc9c8!important;color:#28585d!important}
    html[data-anon-theme="mix"] .chatScreenShell{background:#c7d5d6!important}html[data-anon-theme="mix"] .chatScreenBody{background:radial-gradient(circle at 12% 2%,rgba(64,112,148,.10),transparent 25%),radial-gradient(circle at 88% 90%,rgba(73,127,95,.11),transparent 27%),#c7d5d6!important}
    html[data-anon-theme="mix"] .bubble.left{background:#d8e3e1!important;border-color:rgba(40,66,70,.13)!important;color:#213039!important}html[data-anon-theme="mix"] .bubble.right{background:linear-gradient(135deg,#b6ced5,#b9d2c1)!important;border-color:#9dbfc0!important;color:#24404a!important}
    html[data-anon-theme="mix"] .dayPill,html[data-anon-theme="mix"] .reactionPill,html[data-anon-theme="mix"] .replyComposerBar,html[data-anon-theme="mix"] .attachButton{background:#cfdcdb!important;border-color:rgba(40,66,70,.13)!important}
    html[data-anon-theme="mix"] .chatComposer{background:linear-gradient(180deg,rgba(199,213,214,0),rgba(199,213,214,.95) 22%,#c7d5d6)!important}html[data-anon-theme="mix"] .chatComposer textarea{background:#d6e1e0!important}
    html[data-anon-theme="mix"] .actionSheet{background:#d3dedd!important}html[data-anon-theme="mix"] .actionPreview,html[data-anon-theme="mix"] .reactionPicker button,html[data-anon-theme="mix"] .actionGrid button,html[data-anon-theme="mix"] .forwardTarget{background:#c6d4d4!important}

    html[data-anon-theme="blue"]{background:#c8d7e5!important;color-scheme:light}
    html[data-anon-theme="blue"] body{background:radial-gradient(circle at 8% -5%,rgba(66,105,155,.20),transparent 31%),#c8d7e5!important;color:#203144!important}
    html[data-anon-theme="blue"] .card,html[data-anon-theme="blue"] .messengerList,html[data-anon-theme="blue"] .stat,html[data-anon-theme="blue"] .contact{background:#d8e3ed!important;border-color:rgba(46,72,104,.15)!important}
    html[data-anon-theme="blue"] input,html[data-anon-theme="blue"] textarea,html[data-anon-theme="blue"] #messageBody{background:#cedbe6!important;border-color:rgba(46,72,104,.16)!important;color:#203144!important}
    html[data-anon-theme="blue"] .messengerTop,html[data-anon-theme="blue"] .chatScreenHeader,html[data-anon-theme="blue"] .nav{background:rgba(197,212,226,.97)!important}html[data-anon-theme="blue"] .nav button.active,html[data-anon-theme="blue"] .filterChip.active{background:#afc5dc!important;color:#315d85!important}
    html[data-anon-theme="blue"] .chatScreenShell,html[data-anon-theme="blue"] .chatScreenBody{background:#c5d4e2!important}html[data-anon-theme="blue"] .bubble.left{background:#d8e3ec!important;color:#203144!important}html[data-anon-theme="blue"] .bubble.right{background:#adc7df!important;border-color:#91b2d0!important;color:#244866!important}
    html[data-anon-theme="blue"] .chatComposer{background:linear-gradient(180deg,rgba(197,212,226,0),rgba(197,212,226,.96) 22%,#c5d4e2)!important}html[data-anon-theme="blue"] .chatComposer textarea,html[data-anon-theme="blue"] .actionSheet{background:#d5e0ea!important}

    html[data-anon-theme="green"]{background:#cbdccf!important;color-scheme:light}
    html[data-anon-theme="green"] body{background:radial-gradient(circle at 95% -5%,rgba(64,125,91,.19),transparent 31%),#cbdccf!important;color:#23382d!important}
    html[data-anon-theme="green"] .card,html[data-anon-theme="green"] .messengerList,html[data-anon-theme="green"] .stat,html[data-anon-theme="green"] .contact{background:#dbe6dd!important;border-color:rgba(45,79,59,.14)!important}
    html[data-anon-theme="green"] input,html[data-anon-theme="green"] textarea,html[data-anon-theme="green"] #messageBody{background:#d0ddd3!important;border-color:rgba(45,79,59,.16)!important;color:#23382d!important}
    html[data-anon-theme="green"] .messengerTop,html[data-anon-theme="green"] .chatScreenHeader,html[data-anon-theme="green"] .nav{background:rgba(202,218,206,.97)!important}html[data-anon-theme="green"] .nav button.active,html[data-anon-theme="green"] .filterChip.active{background:#b7d0bd!important;color:#356147!important}
    html[data-anon-theme="green"] .chatScreenShell,html[data-anon-theme="green"] .chatScreenBody{background:#c8d9cc!important}html[data-anon-theme="green"] .bubble.left{background:#dbe5dd!important;color:#23382d!important}html[data-anon-theme="green"] .bubble.right{background:#b7d2bf!important;border-color:#9bc2a8!important;color:#2a5037!important}
    html[data-anon-theme="green"] .chatComposer{background:linear-gradient(180deg,rgba(200,217,204,0),rgba(200,217,204,.96) 22%,#c8d9cc)!important}html[data-anon-theme="green"] .chatComposer textarea,html[data-anon-theme="green"] .actionSheet{background:#d7e2d9!important}

    html[data-anon-theme="gray"]{background:#cfd4da!important;color-scheme:light}
    html[data-anon-theme="gray"] body{background:linear-gradient(150deg,#cfd4da,#c8ced5)!important;color:#29323c!important}
    html[data-anon-theme="gray"] .card,html[data-anon-theme="gray"] .messengerList,html[data-anon-theme="gray"] .stat,html[data-anon-theme="gray"] .contact{background:#dce1e6!important;border-color:rgba(51,61,72,.14)!important}
    html[data-anon-theme="gray"] input,html[data-anon-theme="gray"] textarea,html[data-anon-theme="gray"] #messageBody{background:#d2d8de!important;color:#29323c!important;border-color:rgba(51,61,72,.15)!important}
    html[data-anon-theme="gray"] .messengerTop,html[data-anon-theme="gray"] .chatScreenHeader,html[data-anon-theme="gray"] .nav{background:rgba(205,211,217,.97)!important}html[data-anon-theme="gray"] .nav button.active,html[data-anon-theme="gray"] .filterChip.active{background:#bac4ce!important;color:#465767!important}
    html[data-anon-theme="gray"] .chatScreenShell,html[data-anon-theme="gray"] .chatScreenBody{background:#cbd1d7!important}html[data-anon-theme="gray"] .bubble.left{background:#dce1e5!important;color:#29323c!important}html[data-anon-theme="gray"] .bubble.right{background:#bcc9d1!important;border-color:#a6b6c0!important;color:#344852!important}
    html[data-anon-theme="gray"] .chatComposer{background:linear-gradient(180deg,rgba(203,209,215,0),rgba(203,209,215,.96) 22%,#cbd1d7)!important}html[data-anon-theme="gray"] .chatComposer textarea,html[data-anon-theme="gray"] .actionSheet{background:#d7dce1!important}

    html[data-anon-theme="night"]{background:#1c2830!important;color-scheme:dark}
    html[data-anon-theme="night"] body{background:radial-gradient(circle at 8% -5%,rgba(54,107,135,.22),transparent 30%),radial-gradient(circle at 98% 0,rgba(63,118,88,.18),transparent 27%),#1c2830!important;color:#e4edf0!important}
    html[data-anon-theme="night"] .card,html[data-anon-theme="night"] .messengerList,html[data-anon-theme="night"] .stat,html[data-anon-theme="night"] .contact{background:#26343c!important;border-color:rgba(180,205,211,.12)!important;color:#e4edf0!important}
    html[data-anon-theme="night"] .muted,html[data-anon-theme="night"] .small{color:#aab9bf!important}html[data-anon-theme="night"] input,html[data-anon-theme="night"] textarea,html[data-anon-theme="night"] #messageBody{background:#213038!important;color:#e4edf0!important;border-color:rgba(180,205,211,.14)!important}
    html[data-anon-theme="night"] .messengerTop,html[data-anon-theme="night"] .chatScreenHeader,html[data-anon-theme="night"] .nav{background:rgba(28,40,48,.97)!important}html[data-anon-theme="night"] .nav button.active,html[data-anon-theme="night"] .filterChip.active{background:#365058!important;color:#d9f0e9!important}
    html[data-anon-theme="night"] .chatScreenShell,html[data-anon-theme="night"] .chatScreenBody{background:#1f2d34!important}html[data-anon-theme="night"] .bubble.left{background:#2b3940!important;color:#e4edf0!important}html[data-anon-theme="night"] .bubble.right{background:linear-gradient(135deg,#35566a,#3f6750)!important;color:#f1f7f5!important;border-color:#4b7071!important}
    html[data-anon-theme="night"] .chatComposer{background:linear-gradient(180deg,rgba(31,45,52,0),rgba(31,45,52,.96) 22%,#1f2d34)!important}html[data-anon-theme="night"] .chatComposer textarea,html[data-anon-theme="night"] .actionSheet{background:#2a3840!important;color:#e4edf0!important}

    .anonThemeButton{width:38px;height:38px;padding:0!important;border-radius:50%!important;display:grid;place-items:center;font-size:17px!important;background:rgba(88,117,121,.14)!important;border:1px solid rgba(60,82,87,.15)!important;color:inherit!important;box-shadow:none!important;flex:0 0 38px}
    .brand .anonThemeButton{margin-left:auto}.anonThemeBackdrop{position:fixed;inset:0;z-index:120;background:rgba(34,46,51,.30);display:flex;align-items:flex-end;justify-content:center;padding:12px}.anonThemeSheet{width:min(100%,520px);border-radius:24px;padding:15px;background:#d9e3e2;border:1px solid rgba(40,66,70,.16);box-shadow:0 -18px 55px rgba(35,49,54,.20)}.anonThemeSheet h3{margin:2px 0 4px;color:#24363b}.anonThemeSheet p{margin:0 0 12px;color:#63747b;font-size:12px}.anonThemeChoices{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.anonThemeChoice{display:flex;align-items:center;gap:10px;text-align:left;padding:11px!important;border-radius:16px!important;background:#cedbd9!important;border:1px solid rgba(40,66,70,.13)!important;color:#2f444b!important}.anonThemeChoice.active{outline:2px solid rgba(58,111,112,.48);background:#c2d4d1!important}.anonThemeSwatch{width:34px;height:34px;border-radius:12px;flex:0 0 34px;border:1px solid rgba(30,45,50,.12)}.anonThemeChoice b{display:block;font-size:12px}.anonThemeChoice span:last-child{display:block;font-size:9px;opacity:.72;margin-top:2px}.anonThemeClose{width:100%;margin-top:10px;background:#c4d2d1!important;color:#365159!important;border:1px solid rgba(40,66,70,.13)!important}.anonThemeSettings{display:grid;gap:9px;padding:12px;border-radius:17px;background:rgba(82,117,118,.08);border:1px solid rgba(60,86,88,.12)}.anonThemeSettings strong{font-size:13px}.anonThemeSettings .anonThemeChoices{grid-template-columns:repeat(2,1fr)}
    @media(max-width:420px){.anonThemeChoices{grid-template-columns:1fr 1fr}.anonThemeChoice{padding:9px!important}.anonThemeSwatch{width:30px;height:30px;flex-basis:30px}}
'''
html=html.replace('</style>',css+'\n  </style>',1)

js=r'''var ANON_THEMES={mix:{label:'Mixte',desc:'Bleu · vert · gris',meta:'#cad8d8',swatch:'linear-gradient(135deg,#9fbcc8,#a8c7b0 55%,#aeb8c1)'},blue:{label:'Bleu',desc:'Bleu doux et gris',meta:'#c8d7e5',swatch:'linear-gradient(135deg,#9eb9d2,#c2d0df)'},green:{label:'Vert',desc:'Vert sauge et gris',meta:'#cbdccf',swatch:'linear-gradient(135deg,#9dbfa8,#c7d5cc)'},gray:{label:'Gris',desc:'Ardoise clair',meta:'#cfd4da',swatch:'linear-gradient(135deg,#abb5bf,#d0d4d8)'},night:{label:'Nuit',desc:'Sombre bleu-vert',meta:'#1c2830',swatch:'linear-gradient(135deg,#294554,#365b47)'}};
function currentAnonTheme(){try{return localStorage.getItem('anonbox_theme_v1')||'mix'}catch(e){return 'mix'}}
function applyAnonTheme(name,save){if(!ANON_THEMES[name])name='mix';document.documentElement.setAttribute('data-anon-theme',name);document.documentElement.style.colorScheme=name==='night'?'dark':'light';var meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content',ANON_THEMES[name].meta);if(save!==false){try{localStorage.setItem('anonbox_theme_v1',name)}catch(e){}}refreshAnonThemeUI();try{if(window.AnonBoxThemeBridge&&typeof window.AnonBoxThemeBridge.setTheme==='function')window.AnonBoxThemeBridge.setTheme(name)}catch(e){}}
function anonThemeChoicesHtml(){var active=currentAnonTheme();return Object.keys(ANON_THEMES).map(function(k){var t=ANON_THEMES[k];return '<button type="button" class="anonThemeChoice '+(active===k?'active':'')+'" data-anon-theme-choice="'+k+'"><span class="anonThemeSwatch" style="background:'+t.swatch+'"></span><span><b>'+t.label+'</b><span>'+t.desc+'</span></span></button>'}).join('')}
function refreshAnonThemeUI(){document.querySelectorAll('[data-anon-theme-choice]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-anon-theme-choice')===currentAnonTheme())});var label=$('anonThemeCurrentLabel');if(label)label.textContent=ANON_THEMES[currentAnonTheme()].label}
function bindAnonThemeChoices(root){(root||document).querySelectorAll('[data-anon-theme-choice]').forEach(function(b){b.onclick=function(){applyAnonTheme(b.getAttribute('data-anon-theme-choice'),true);setTimeout(closeAnonThemePicker,90)}})}
function ensureAnonThemePicker(){if($('anonThemeBackdrop'))return;var d=document.createElement('div');d.id='anonThemeBackdrop';d.className='anonThemeBackdrop hidden';d.innerHTML='<div class="anonThemeSheet" role="dialog" aria-modal="true"><h3>Choisir le thème</h3><p>Le choix est mémorisé sur cet appareil.</p><div class="anonThemeChoices">'+anonThemeChoicesHtml()+'</div><button id="anonThemeClose" type="button" class="anonThemeClose">Fermer</button></div>';document.body.appendChild(d);d.onclick=function(e){if(e.target===d)closeAnonThemePicker()};$('anonThemeClose').onclick=closeAnonThemePicker;bindAnonThemeChoices(d)}
function openAnonThemePicker(){ensureAnonThemePicker();var choices=$('anonThemeBackdrop').querySelector('.anonThemeChoices');choices.innerHTML=anonThemeChoicesHtml();bindAnonThemeChoices($('anonThemeBackdrop'));$('anonThemeBackdrop').classList.remove('hidden')}
function closeAnonThemePicker(){var d=$('anonThemeBackdrop');if(d)d.classList.add('hidden')}
function installAnonThemeControls(){applyAnonTheme(currentAnonTheme(),false);var brand=document.querySelector('#normalShell>.brand');if(brand&&!$('anonThemeBrandBtn')){var b=document.createElement('button');b.id='anonThemeBrandBtn';b.type='button';b.className='anonThemeButton';b.setAttribute('aria-label','Choisir le thème');b.textContent='🎨';b.onclick=openAnonThemePicker;brand.appendChild(b)}var actions=document.querySelector('.topActions');if(actions&&!$('anonThemeTopBtn')){var t=document.createElement('button');t.id='anonThemeTopBtn';t.type='button';t.className='anonThemeButton';t.setAttribute('aria-label','Choisir le thème');t.textContent='🎨';t.onclick=openAnonThemePicker;actions.insertBefore(t,actions.firstChild)}var grid=document.querySelector('#settingsTab .settingGrid');if(grid&&!$('anonThemeSettings')){var block=document.createElement('div');block.id='anonThemeSettings';block.className='anonThemeSettings';block.innerHTML='<strong>🎨 Apparence</strong><div class="small muted">Thème actuel : <span id="anonThemeCurrentLabel"></span></div><div class="anonThemeChoices">'+anonThemeChoicesHtml()+'</div>';grid.insertBefore(block,$('saveSettings'));bindAnonThemeChoices(block)}refreshAnonThemeUI()}
'''
anchor="    bindAnonProfileControls();\n"
if anchor not in html: raise SystemExit('theme JS anchor missing')
html=html.replace(anchor,"    "+js+"\n    installAnonThemeControls();\n"+anchor,1)

INDEX.write_text(html,encoding='utf-8')
sw=SW.read_text(encoding='utf-8').replace("const CACHE='anonbox-v16';","const CACHE='anonbox-v17';")
SW.write_text(sw,encoding='utf-8')
VERSION.write_text('AnonBox web UI v7\nDefault theme: mixed blue-green-gray with no pure-white surfaces\nUser-selectable themes: Mixte, Bleu, Vert, Gris, Nuit\nTheme choice stored locally on device\nAnonymous profile features unchanged\nCache: anonbox-v17\n',encoding='utf-8')
